PREFIX schema: <http://schema.org/>

SELECT ?project ?projectLabel ?article ?repo WHERE {
  # Free Software projects
  ?project p:P31/ps:P31 wd:Q341.

  ?project wdt:P1324 ?repo.

  # Exclude projects not hosted on github
  FILTER(STRSTARTS(STR(?repo), "https://github.com")).

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }

  # Get the corresponding wikipedia page
  ?article schema:about ?project .
  ?article schema:inLanguage "en" .
  ?article schema:isPartOf <https://en.wikipedia.org/>
}
ORDER BY ?projectLabel
